// Generates a self-contained Quantower C# indicator with the current GEX levels
// baked in. Quantower indicators cannot make HTTP calls, so the app pre-computes
// the gamma profile and emits a C# script the user pastes into Quantower's
// Algo → Scripts editor and compiles.
//
// Levels are baked in the symbol's own price units (no auto-scaling — apply the
// indicator to the same instrument you exported from).

import type { StrikeAggregate } from "./analytics";

export interface GenerateQuantowerInput {
  symbol: string;
  exp?: string;
  spot: number;
  aggs: StrikeAggregate[];
  flip: number | null;
  pain: number | null;
  callWall: number | null;
  putWall: number | null;
  generatedAt: string;
}

const MAX_STRIKES = 40;

function round(n: number, dp: number): number {
  const f = 10 ** dp;
  return Math.round(n * f) / f;
}

function csNum(n: number | null): string {
  return n == null || !Number.isFinite(n) ? "double.NaN" : String(n);
}

/** Format a double[] array literal for C#. */
function csArr(xs: number[]): string {
  return xs.length ? `{ ${xs.join(", ")} }` : "{ }";
}

/** Median step between adjacent strikes. */
function medianStep(strikes: number[]): number {
  if (strikes.length < 2) return 1;
  const sorted = [...strikes].sort((a, b) => a - b);
  const diffs: number[] = [];
  for (let i = 1; i < sorted.length; i++) {
    const d = sorted[i] - sorted[i - 1];
    if (d > 0) diffs.push(d);
  }
  if (diffs.length === 0) return 1;
  diffs.sort((a, b) => a - b);
  return diffs[Math.floor(diffs.length / 2)];
}

export function generateQuantowerScript(input: GenerateQuantowerInput): string {
  const selected = [...input.aggs]
    .filter((a) => Number.isFinite(a.netGammaNotional))
    .sort((a, b) => Math.abs(b.netGammaNotional) - Math.abs(a.netGammaNotional))
    .slice(0, MAX_STRIKES)
    .sort((a, b) => a.strike - b.strike);

  const strikes = selected.map((a) => round(a.strike, 2));
  const gex = selected.map((a) => round(a.netGammaNotional, 0));
  const maxAbs = gex.reduce((m, g) => Math.max(m, Math.abs(g)), 0);
  const step = round(medianStep(input.aggs.map((a) => a.strike)), 4);

  const totalGamma = input.aggs.reduce(
    (a, s) => a + (Number.isFinite(s.netGammaNotional) ? s.netGammaNotional : 0),
    0
  );
  const longGamma = totalGamma >= 0;

  const expLabel = input.exp ?? "all";
  const sym = input.symbol.toUpperCase();

  const callBias = longGamma ? "REJECT/FADE" : "BREACH=CHASE";
  const putBias  = longGamma ? "BOUNCE"      : "BREAK=FLUSH";
  const flipBias = longGamma ? "RECLAIM=STABILIZE / LOSE=EXPAND" : "RECLAIM=REVERSE UP";

  return `// ╔══════════════════════════════════════════════════════════════════╗
// ║  A+ GEX Levels — generated by the A+ options app                  ║
// ║  Source: ${sym}   Exp: ${expLabel}   Spot: ${round(input.spot, 2)}
// ║  Generated: ${input.generatedAt}
// ║  Regime: ${longGamma ? "LONG gamma (dealers dampen)" : "SHORT gamma (dealers amplify)"}
// ║                                                                    ║
// ║  How to install:                                                   ║
// ║  1. Open Quantower → Algo → Scripts                                ║
// ║  2. Create a new script, paste this entire file, click Compile     ║
// ║  3. Apply the indicator to a chart of ${sym}               ║
// ║  Levels are baked in ${sym} price units — apply to the same        ║
// ║  instrument you exported from. Re-export for fresh GEX.            ║
// ╚══════════════════════════════════════════════════════════════════╝

using System;
using System.Drawing;
using TradingPlatform.BusinessLayer;

namespace QuantowerAlgo
{
    [Indicator("A+ GEX Levels - ${sym}", "GEX ${sym}", 1,
        Description = "GEX levels from A+ options app (${sym} ${expLabel}, generated ${input.generatedAt})")]
    public class APlus_GEX_Levels_${sym.replace(/[^A-Za-z0-9]/g, "_")} : Indicator
    {
        // ── Baked data (${sym} price units) ──────────────────────────────
        private static readonly double[] Strikes  = new double[] ${csArr(strikes)};
        private static readonly double[] GexVals  = new double[] ${csArr(gex)};
        private const double MaxAbsGex    = ${maxAbs};
        private const double StrikeStep   = ${step};
        private const double SpotAtExport = ${round(input.spot, 2)};
        private const double GammaFlip    = ${csNum(input.flip)};
        private const double CallWall     = ${csNum(input.callWall)};
        private const double PutWall      = ${csNum(input.putWall)};
        private const double MaxPain      = ${csNum(input.pain)};
        private const bool   LongGamma    = ${longGamma ? "true" : "false"};

        // ── Reversal-bias labels (matches A+ website insights) ───────────
        private const string CallBias = "${callBias}";
        private const string PutBias  = "${putBias}";
        private const string FlipBias = "${flipBias}";

        // ── User inputs ───────────────────────────────────────────────────
        [InputParameter("Show GEX bars", 0)]
        public bool ShowGexBars = true;

        [InputParameter("Show key levels", 1)]
        public bool ShowKeyLevels = true;

        [InputParameter("Show reversal bias labels", 2)]
        public bool ShowBias = true;

        [InputParameter("Show spot-at-export line", 3)]
        public bool ShowSpot = true;

        [InputParameter("Bar max width (% of chart width)", 4, 1, 50)]
        public int BarWidthPct = 15;

        // ── A+ palette ────────────────────────────────────────────────────
        private static readonly Color BullColor    = Color.FromArgb(95,  211, 154);  // #5fd39a
        private static readonly Color BearColor    = Color.FromArgb(240, 106, 122);  // #f06a7a
        private static readonly Color NeutralColor = Color.FromArgb(140, 140, 152);  // #8c8c98
        private static readonly Color TextColor    = Color.FromArgb(230, 230, 234);  // #e6e6ea
        private static readonly Color PainColor    = Color.FromArgb(90,  140, 140, 152);

        public APlus_GEX_Levels_${sym.replace(/[^A-Za-z0-9]/g, "_")}() : base()
        {
            this.Name = "A+ GEX Levels";
            this.Description = "GEX levels — ${sym} ${expLabel} — A+ options app";
            this.SeparateWindow = false;
        }

        protected override void OnInit() { }

        protected override void OnCalculate(int bar, double price) { }

        public override void OnPaintChart(PaintChartEventArgs args)
        {
            var gr   = args.Graphics;
            var rect = args.Rectangle;
            var conv = this.CurrentChart.MainWindow.CoordinatesConverter;

            float rightX      = rect.Right  - 5f;
            float barMaxWidth = rect.Width * BarWidthPct / 100f;
            float halfH       = StrikeStep > 0
                ? Math.Abs((float)conv.GetChartY(0) - (float)conv.GetChartY(StrikeStep)) * 0.40f
                : 6f;

            // ── GEX profile bars ─────────────────────────────────────────
            if (ShowGexBars && Strikes.Length > 0)
            {
                for (int i = 0; i < Strikes.Length; i++)
                {
                    float y  = (float)conv.GetChartY(Strikes[i]);
                    if (y < rect.Top - halfH || y > rect.Bottom + halfH) continue;

                    float barW = MaxAbsGex > 0
                        ? (float)(Math.Abs(GexVals[i]) / MaxAbsGex * barMaxWidth)
                        : 4f;
                    barW = Math.Max(barW, 2f);

                    Color c = GexVals[i] >= 0 ? BullColor : BearColor;
                    using (var brush = new SolidBrush(Color.FromArgb(80, c.R, c.G, c.B)))
                    using (var pen   = new Pen(c, 1f))
                    {
                        float top    = y - halfH;
                        float height = halfH * 2f;
                        gr.FillRectangle(brush, rightX - barW, top, barW, height);
                        gr.DrawRectangle(pen,   rightX - barW, top, barW, height);
                    }
                }
            }

            // ── Key levels ────────────────────────────────────────────────
            if (ShowKeyLevels)
            {
                if (!double.IsNaN(GammaFlip))
                    DrawLevel(gr, rect, conv, GammaFlip, NeutralColor, 2f,
                        "GAMMA FLIP  [" + FlipBias + "]", ShowBias);
                if (!double.IsNaN(CallWall))
                    DrawLevel(gr, rect, conv, CallWall, BullColor, 2f,
                        "CALL WALL  [" + CallBias + "]", ShowBias);
                if (!double.IsNaN(PutWall))
                    DrawLevel(gr, rect, conv, PutWall, BearColor, 2f,
                        "PUT WALL  [" + PutBias + "]", ShowBias);
                if (!double.IsNaN(MaxPain))
                    DrawLevel(gr, rect, conv, MaxPain, PainColor, 1f,
                        "MAX PAIN  magnet", ShowBias);
            }

            if (ShowSpot)
                DrawLevel(gr, rect, conv, SpotAtExport, Color.FromArgb(120, TextColor.R, TextColor.G, TextColor.B),
                    1f, "SPOT @ export", false);
        }

        private static void DrawLevel(
            Graphics gr, Rectangle rect,
            IChartCoordinatesConverter conv,
            double price, Color color, float lineWidth,
            string label, bool showLabel)
        {
            float y = (float)conv.GetChartY(price);
            if (y < rect.Top || y > rect.Bottom) return;

            using (var pen = new Pen(color, lineWidth) { DashStyle = System.Drawing.Drawing2D.DashStyle.Dash })
                gr.DrawLine(pen, rect.Left, y, rect.Right, y);

            if (showLabel)
            {
                string text = label + "  " + price.ToString("F2");
                using (var font  = new Font("Consolas", 7.5f, FontStyle.Regular))
                using (var brush = new SolidBrush(color))
                {
                    var sz = gr.MeasureString(text, font);
                    gr.DrawString(text, font, brush, rect.Right - sz.Width - 8f, y - sz.Height - 2f);
                }
            }
        }
    }
}
`;
}
